// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpEnvVar } from "./AcpEnvVar";

export type AcpCreateTerminalRequest = { command: string, args: Array<string>, cwd: string | null, env: Array<AcpEnvVar>, outputByteLimit: number | null, };
