// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpExitStatus } from "./AcpExitStatus";

export type AcpTerminalOutputResponse = { output: string, truncated: boolean, cwd: string | null, exitStatus: AcpExitStatus | null, };
