// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerConfig } from "./McpServerConfig";

export type ConnectionNewSessionRequest = { connectionId: string, cwd: string, mcpServers: Array<McpServerConfig>, };
