// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DocumentOpenResponse = { content: string, encoding: string, lineEnding: string, languageId: string, version: number, isDirty: boolean, isReadonly: boolean, isLargeFile: boolean, lineCount: number, };
