// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShellInfo } from "./ShellInfo";

export type GetAvailableShellsResponse = { shells: Array<ShellInfo>, };
