// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetFileChangeResponse = { path: string | null, oldContent: string | null, newContent: string | null, kind: string | null, };
