// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileState } from "./TileState";

export type GetTileStatesResponse = { tiles: Array<TileState>, };
