// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type InitConnectionResponse = { connectionId: string, agentId: string, configOptions: JsonValue | null, modes: JsonValue | null, };
