// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerConfig } from "./McpServerConfig";

export type LoadSessionRequest = { sessionId: string, targetSessionId: string, cwd: string, mcpServers: Array<McpServerConfig>, };
