// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvVar } from "./EnvVar";
import type { HttpHeader } from "./HttpHeader";

export type McpTransport = { "type": "stdio", command: string, args: Array<string>, env: Array<EnvVar>, } | { "type": "http", url: string, headers: Array<HttpHeader>, } | { "type": "sse", url: string, headers: Array<HttpHeader>, };
