// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpTransport = { "type": "stdio", command: string, args: Array<string>, } | { "type": "http", url: string, } | { "type": "sse", url: string, };
