// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveAgentProfileRequest = { name: string, maxRetriesPerStep: number, maxCompactTokens: number, prompt: string, };
