// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveExplorerStateRequest = { expandedDirs: string, activeFile: string | null, workspace: string | null, };
