// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSearchResult } from "./FileSearchResult";

export type SearchFilesResponse = { files: Array<FileSearchResult>, };
