// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionListEntry = { sessionId: string, title: string, createdAt: string, updatedAt: string, messageCount: number, };
