// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalSpawnRequest = { shell: string | null, cwd: string | null, cols: number | null, rows: number | null, };
