// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceChild } from "./WorkspaceChild";

export type WorkspaceExpandResponse = { children: Array<WorkspaceChild>, };
