#!/bin/bash

if type update-alternatives 2>/dev/null >&1; then
    # Remove previous link if it doesn't use update-alternatives
    if [ -L '/usr/bin/crow-ui' -a -e '/usr/bin/crow-ui' -a "`readlink '/usr/bin/crow-ui'`" != '/etc/alternatives/crow-ui' ]; then
        rm -f '/usr/bin/crow-ui'
    fi
    update-alternatives --install '/usr/bin/crow-ui' 'crow-ui' '/opt/crow-ui/crow-ui' 100 || ln -sf '/opt/crow-ui/crow-ui' '/usr/bin/crow-ui'
else
    ln -sf '/opt/crow-ui/crow-ui' '/usr/bin/crow-ui'
fi

if hash update-mime-database 2>/dev/null; then
    update-mime-database /usr/share/mime || true
fi

if hash update-desktop-database 2>/dev/null; then
    update-desktop-database /usr/share/applications || true
fi
